---
name: Features

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  job-1:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -la
      - run: pwd
      - uses: actions/checkout@v4
      - run: ls -la
      - run: touch test.txt
      - run: ls -la
      - run: pwd
  job-2:
    needs: [job-1]
    if: failure() || success()
    runs-on: ubuntu-22.04
    steps:
      - run: pwd
      - uses: actions/checkout@v4
      - run: pwd
      - run: echo -----
      - run: ip a
  job-3:
    runs-on: ubuntu-22.04
    container:  # Run the current job in the container defined below. Btw. default registry is Docker Hub, if you want to use e.g. GHCR then use "ghcr.io/owner/image". Of course you can use your own image like e.g. "image: jakubszuber/testing_image"
      image: node:16
      env:
        NODE_ENV: testing
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - run: whoami
      - run: cat /etc/passwd
      - name: Get Code
        uses: actions/checkout@v3
      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0  # x-release-please-version
      # - uses: docker-practice/actions-setup-docker@master
      #   timeout-minutes: 12
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
