---
  name: Features-2

  on:
    workflow_dispatch:
    pull_request:
    push:

  jobs:
    job-1:
      runs-on: ubuntu-22.04
      steps:
        - run: pwd
        - uses: actions/checkout@v4
        - run: pwd
        - run: echo -----
        - run: ip a
    jobb-2:
      runs-on: ubuntu-22.04
      steps:
        - run: pwd
        - uses: actions/checkout@v4
        - run: pwd
        - run: echo -----
        - run: ip a
