---
name: Features

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v4
      - run: pwd
      - run: echo -----
      - run: ip a
  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v4
      - run: pwd
      - run: echo -----
      - run: ip a
  job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
